resources:
  - ./certificate.yaml
  - ./grafana-ingress.yaml
  - ./grafana-service.yaml
  - ./grafana-statefulset.yaml

labels:
  - pairs:
      # use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
      app.jimwilleke.com/name: grafana
      # NOTE: tenet is specified in the overlays
      #app.jimwilleke.com/tenant:
