namespace: monitoring

resources:
  - ./certificate.yaml
  - ./grafana-ingress.yaml
  - ./grafana-service.yaml
  - ./grafana-statefulset.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - config/provisioning/datasources/prometheus.yaml
  - name: grafana-dashboard-providers
    files:
      - config/provisioning/dashboards/dashboards.yaml
  - name: grafana-dashboards
    files:
      - config/dashboards/jimstest-wiki.json

labels:
  - pairs:
      # use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
      app.jimwilleke.com/name: grafana
      # NOTE: tenet is specified in the overlays
      #app.jimwilleke.com/tenant:
