resources:
  - ./namespace.yaml
  # - ./kube-state-metrics  # DISABLED: Missing base resources at ../../../base/monitoring/kube-state-metrics
  - ../../base/monitoring/kube-state-metrics/  # 2026-01-01 Added this line
  - ./prometheus
  - ./prometheus-alertmanager
  - ./prometheus-blackbox-exporter
  - ./grafana
  - ./otel-collector

namespace: monitoring

# NOTE: adding `managedByLabel` here causes a label like `app.kubernetes.io/managed-by: kustomize-(devel)` to be added and `kustomize-(devel)` gets rejected by k8s server side.
buildMetadata: [originAnnotations, transformerAnnotations]
# setting commonLabels in each of grafana and prometheus folders above
#commonLabels:
# use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
# app.jimwilleke.com/name: monitoring
# NOTE: tenet is specified in the overlays
#app.jimwilleke.com/tenant:
