apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-resources
  namespace: shared-resources
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - cdn.nerdsbythehour.com
    secretName: shared-resources-tls
  rules:
  - host: cdn.nerdsbythehour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shared-resources
            port:
              name: http
