resources:
  - namespace.yaml
  - ../../../base/photoprism
  - certificate.yaml

patches:
  - path: patch-mariadb-volume.yaml
  - path: patch-photoprism-statefulset.yaml
  - path: patch-photoprism-ingress.yaml

namespace: photoprism-oksana

labels:
  - pairs:
      app.jimwilleke.com/tenant: oksana
