apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    # Using OIDC auth directly in HA instead of ForwardAuth
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ha.nerdsbythehour.com
    secretName: home-assistant-tls
  rules:
  - host: ha.nerdsbythehour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant-external
            port:
              number: 8123
