apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.nerdsbythehour.com`)
      kind: Rule
      middlewares:
        - name: authentik-forwardauth
          namespace: authentik
      services:
        - name: home-assistant-external
          port: 8123
          scheme: http
  tls:
    certResolver: letsencrypt-production
    domains:
      - main: ha.nerdsbythehour.com
