apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant-proxy
resources:
  - namespace.yaml
  - external-service.yaml
  - serverstransport.yaml
  - ingress.yaml
  - certificate.yaml
