apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jimsmcp
  namespace: jimsmcp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - jimsmcp.nerdsbythehour.com
    secretName: jimsmcp-tls
  rules:
  - host: jimsmcp.nerdsbythehour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jimsmcp
            port:
              number: 9210
