apiVersion: v1
kind: Service
metadata:
  name: jimsmcp
  namespace: jimsmcp
spec:
  selector:
    app: jimsmcp
  ports:
  - name: http
    port: 9210
    targetPort: 9210
    protocol: TCP
  type: ClusterIP
