apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging

resources:
  - namespace.yaml
  - mosquitto-pv.yaml
  - mosquitto-pvc.yaml
  - mosquitto-configmap.yaml
  - mosquitto-deployment.yaml
  - mosquitto-service.yaml
