# Reference:
# - https://cert-manager.io/docs/concepts/certificate/
# - https://cert-manager.io/docs/usage/certificate/
# - tutorial: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hoard-nerdsbythehour-com
spec:
  # the secret is put here and matches a value in the ingress
  secretName: hoard-nerdsbythehour-com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hoard.jimwilleke.com
  dnsNames:
    - hoard.jimwilleke.com
