apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoarder-web-ingress
  namespace: hoarder
spec:
  tls:
    - hosts:
        - hoard.jimwilleke.com
      # There must be a Certificate resource created that saves to this secret name
      secretName: hoard-nerdsbythehour-com
  rules:
    - host: "hoard.jimwilleke.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "web"
                port:
                  number: 3000
