scrape_configs:
  # Scrapes metrics from Prometheus itself
  # No authentication needed since basic auth was removed in favor of Authentik at ingress level
  - job_name: "prometheus self scrape"
    static_configs:
      - targets: ["localhost:9090"]
