apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smb-filebrowser
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - filebrowser.nerdsbythehour.com
    secretName: filebrowser-tls
  rules:
  - host: filebrowser.nerdsbythehour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smb-filebrowser
            port:
              number: 80
