apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
# - oauth2-secret.yaml  # TODO: Configure OIDC authentication later
- configmap.yaml
- deployment.yaml
- service.yaml
# Certificate auto-created by ingress annotation
- ingress.yaml
