apiVersion: v1
kind: Service
metadata:
  name: amdwiki
  namespace: amdwiki
spec:
  selector:
    app: amdwiki
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
