apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teslamate

resources:
  - namespace.yaml
  - teslamate-secret.yaml
  - teslamate-deployment.yaml
  - teslamate-service.yaml
  - teslamate-ingress.yaml
  - teslamate-certificate.yaml
