resources:
  - namespace.yaml
  - rabbitmq-pv.yaml
  - db-pv.yaml
  - db-backup-pv.yaml
  - ../../base/tayle/
  - app-ingress-certificate.yaml
  - image-scanning/tayle-image-scanning.yaml
configurations:
  - image-scanning/secret-name-reference.yaml
patches:
  - path: patch-app-ingress.yaml
  # patch the volume name in the PVC's used in the StatefulSets:
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: tayle-prod-rabbitmq-pv-data
    target:
      kind: StatefulSet
      name: rabbitmq
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: tayle-prod-db-pv-data
    target:
      kind: StatefulSet
      name: db
  # patch the volume name in the PVC used for the db-backup CronJob:
  - target:
      kind: PersistentVolumeClaim
      name: db-backup-pvc
    patch: |-
      - op: replace
        path: /spec/volumeName
        value: tayle-prod-db-backup-pv
namespace: tayle-prod
secretGenerator:
  # db
  - name: db-creds
    envs:
      - .env.secret.db.encrypted
  # rabbit
  - name: rabbitmq-creds
    envs:
      - .env.secret.rabbitmq.encrypted
  # app
  - name: app-creds
    envs:
      - .env.secret.app.encrypted
  # worker:
  - name: worker-creds
    envs:
      - .env.secret.worker.encrypted
  # image pull secret:
  - name: github-container-registry-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=ghcr.dockeronfigjson.encrypted
# the images tag: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_imagetagtransformer_
# the imagepolicy markers: https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources
images:
  - name: tayle-image-app
    newName: ghcr.io/activescott/tayle/app # {"$imagepolicy": "tayle-prod:policy-tayle-app:name"}
    newTag: 1.28.0 # {"$imagepolicy": "tayle-prod:policy-tayle-app:tag"}
  - name: tayle-image-worker
    newName: ghcr.io/activescott/tayle/worker # {"$imagepolicy": "tayle-prod:policy-tayle-worker:name"}
    newTag: 1.28.0 # {"$imagepolicy": "tayle-prod:policy-tayle-worker:tag"}
  - name: tayle-image-db
    newName: postgres
    newTag: "17"
  - name: tayle-image-rabbitmq
    newName: rabbitmq
    newTag: 3-management
