resources:
  - ./scott
  - ./oksana

# NOTE: adding `managedByLabel` here causes a label like `app.kubernetes.io/managed-by: kustomize-(devel)` to be added and `kustomize-(devel)` gets rejected by k8s server side.
buildMetadata: [originAnnotations, transformerAnnotations]

labels:
  - pairs:
      # use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
      app.jimwilleke.com/name: photoprism
      # NOTE: tenet is specified in the overlays
      #app.jimwilleke.com/tenant:
