resources:
  - ./namespace.yaml
  - ../../base/transmission

buildMetadata: [originAnnotations, transformerAnnotations]

labels:
  - pairs:
      # NOTE: metrics-server seems to label all of their resources with `k8s-app: metrics-server`
      # use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
      app.jimwilleke.com/name: transmission

namespace: transmission

secretGenerator:
  - name: transmission-creds
    envs:
      - .env.secret.transmission.encrypted
