apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  labels:
    app.jimwilleke.com/name: grafana
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-authentik-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: grafana.nerdsbythehour.com
    http:
      paths:
      - backend:
          service:
            name: grafana-service
            port:
              name: web-ui
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - grafana.nerdsbythehour.com
    secretName: grafana-nerdsbythehour-com-cert
