apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mjplex
resources:
  - namespace.yaml
  - mjplex-statefulset.yaml
  - mjplex-service.yaml
  - mjplex-ingress.yaml
  - mjplex-certificate.yaml
