apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mjplex
  namespace: mjplex
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # TODO: Enable Authentik ForwardAuth protection
    # traefik.ingress.kubernetes.io/router.middlewares: authentik-forwardauth-mjplex@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - plex.nerdsbythehour.com
    secretName: mjplex-tls
  rules:
  - host: plex.nerdsbythehour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mjplex
            port:
              number: 32400
