resources:
  - ./blackbox-deployment.yaml
  - ./blackbox-service.yaml

configMapGenerator:
  # the blackbox exporter's config:
  - name: blackbox-exporter-config
    files:
      - ./config/blackbox-config.yaml

labels:
  - pairs:
      # use `app.jimwilleke.com/name` to avoid conflicts with other people's resources using "app" label.
      app.jimwilleke.com/name: blackbox-exporter
