apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - namespace.yaml
  - postgresql-pv.yaml
  - postgresql-pvc.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - postgresql-secret.yaml
